[variables]
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["echo install skipped - runtime install enabled"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
